name: Pull Request checker

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request
        uses: tachiyomiorg/issue-moderator-action@v1
        with:
          auto-close-rules: |
            [
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed."
              }
            ]
          auto-close-ignore-label: |
            do-not-autoclose
            bug
            enhancement
